name: Deploy pull request to Pages

on:
  workflow_run:
    workflows:
      - "Flutter Testing"
    types:
      - completed

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out sources
        uses: actions/checkout@v3
