name: Publish dev webapp

on:
  workflow_run:
    workflows:
      - "Flutter Testing"
    types:
      - completed

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get event
        env:
          EVENT: ${{ toJSON(github.event) }}
        run: |
          echo "${EVENT}"

      - name: Get PR number
        env:
          NUMBER: ${{ github.event.number }}
        run: |
          echo "${NUMBER}"

      - name: Get workflow
        env:
          WORKFLOW: ${{ toJSON(github.workflow) }}
        run: |
          echo "${WORKFLOW}"

      - name: Get run_id
        env:
          RUN_ID: ${{ toJSON(github.run_id) }}
        run: |
          echo "${RUN_ID}"

      - name: Get actions runtime URL
        run: |
          echo "${{ env.ACTIONS_RUNTIME_URL }}"

      - name: Check out sources
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Get artifacts
        id: get_workflow_artifacts
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{repository}/actions/runs/{run_id}/artifacts
          repository: ${{ github.repository }}
          run_id: ${{ toJSON(github.run_id) }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Print artifacts
        env:
          artifacts: ${{ toJSON(steps.get_workflow_artifacts.outputs) }}
        run: echo "${artifacts}"

      - name: Get pull request ref
        id: get_pull_request_ref
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{repository}/pulls/{pull_number}
          repository: ${{ github.repository }}
          pull_number: ${{ fromJSON(github.event.number) }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Create deployment
        id: create_deployment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/pages/deployments
          repository: ${{ github.repository }}
          ref: ${{ fromJson(steps.get_pull_request_ref.outputs.data).head.ref }}
          environment: dev-${{ fromJSON(github.event.number) }}
          auto_merge: false
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
