name: Deploy pull request to Pages

on:
  workflow_run:
    workflows:
      - "Flutter Testing"
    types:
      - completed

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out sources
        uses: actions/checkout@v3

      - name: Get artifacts
        id: get_workflow_artifacts
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{repository}/actions/runs/{run_id}/artifacts
          repository: ${{ github.repository }}
          run_id: ${{ toJSON(github.run_id) }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Print artifacts
        env:
          artifacts: ${{ toJSON(steps.get_workflow_artifacts.outputs) }}
        run: echo "${artifacts}"
