name: Deploy static content to Pages

on:
  workflow_run:
    workflows:
      - "Flutter Testing"
    branches:
      - main
    types:
      - completed

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Get target folder
        id: target_folder
        env:
          PR_NUMBER: ${{ toJSON(github.event.workflow_run.pull_requests[0].number) }}
        run: |
          if [[ ${PR_NUMBER} == null ]]; then
            target_folder=""
          else
            target_folder="pr-${PR_NUMBER}"
          fi
          echo target_folder=${target_folder} >> ${GITHUB_ENV}
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build web --base-href /platformer-1/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./build/web

        #- name: Upload artifact
        #  uses: actions/upload-pages-artifact@v1
        #  with:
        #    path: './build/web'
        #- name: Deploy to GitHub Pages
        #  id: deployment
        #  uses: actions/deploy-pages@v1
        #  with:
        #    target-folder: ${{ env.target_folder }}
