name: Remove pull request deployment

on:
  pull_request:
    types: [closed]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  remove:
    runs-on: ubuntu-latest
    steps:
      - name: Check whether PR has deployment
        env:
          EVENT: ${{ toJSON(github.event) }}
        run: true
      - name: Delete deployment
        run: true
      - name: Clean `gh-pages`
        run: true
